---

  - name: restart httpd
    service: 
      name: httpd 
      state: restarted

  - name: start httpd
    service: 
      name: httpd 
      state: started

  - name: stop httpd
    service: 
      name: httpd 
      state: stopped
