---

 # Make sure that libselinux-python is installed (required for Ansible templates)
  - name: Make sure that libselinux-python is installed
    yum: 
      name: libselinux-python 
      state: latest
    tags: [nodejs, install]

  - name: Make sure that Node.js repository is available
    template: 
      src: nodesource-el6.repo.j2 
      dest: /etc/yum.repos.d/nodejs.repo 
      owner: root 
      group: root 
      mode: 0644
    tags: [nodejs, install]
 
  - name: Install Node.js and NPM
    yum: 
      name: "nodejs-{{ nodejs_version }}" 
      state: present
    tags: [nodejs, install]