---

  - name: Installing httpd Latest version of Apache
    yum: 
      name: httpd 
      state: latest
    tags: [httpd]

  - name: Start httpd
    service: 
      name: httpd 
      state: started 
      enabled: yes
    tags: [httpd]

  - name: Check httpd is running
    action: service name=httpd state=running
    tags: [httpd]
